### ISSUE TITLE
Integration with FrontSpot-Moscow

### ISSUE THREAD

**Issue by priestine** [priestine/not-node-school#13]
As soon as we are ready with #1, we can move on to integrating with FrontSpot-Moscow.

- [ ] Move this repository to FrontSpot-Moscow GitHub org
- [ ] Create a space for workshops on Community-Z [here](https://community-z.com/communities/m6zWtf3xHk)

**Comment by priestine** [comment]
@AntonRatnick @tatoshko @datapain @vitasar @Mrdev1ce Guys. What if we make this thing part of https://raini.dev? 😏

**Comment by BodyCount** [comment]
@priestine I think we have to discuss it in the near meeting

**Comment by priestine** [comment]
Closing as going with FSM is not the best option to pick for us.
