### ISSUE TITLE
Pick the topic for first workshop #0

### ISSUE THREAD

**Issue by priestine** [priestine/not-node-school#15]
Let's leave suggestions of some topics so that we can then poll and decide which one we choose.

**Comment by priestine** [comment]
Considering the topics, the ideas I can think of are:

- [ ] AWS three-tier infrastructure
- [ ] Going Serverless (taking an existing app and migrating it to AWS Serverless with DynamoDB, API Gateway, Cognito and Lambdas)
- [ ] REST APIs with Node (REST maturity level 3 implementation)
- [ ] Implementing WebSockets with Node (from the bottom up, no deps)

**Comment by priestine** [comment]
Possible topics discussed on the meeting:

* Accessibility (browser capabilities)
* Debugging browser applications
* X CI hands on
* AWS for Front-end
* Node REST Maturity level 3 hands on
* WebGL
* Something about testing (tools, approaches)
* RxJS?
* Reactive programming?

**Comment by BodyCount** [comment]
Themes I'd like to listen/participate in some of them:

- true fp patterns in js (w/ rambda?)
- building `X` framework from scratch
- creating open source GItHub repo for library `X` (inspired by this repo)
- SVG

**Comment by priestine** [comment]
I'll convert this issue into "Pick topic for the first workshop" to make the process more clear. The rest of the stuff will be moved to a separate issue.

**Comment by priestine** [comment]
As a result of our internal poll, the list was narrowed down to:

- [ ] Accessibility
- [ ] Going Serverless (with AWS)
- [ ] WebSocket protocol with Node from scratch
- [ ] CI hands-on
- [ ] AWS for Front-end developers
- [ ] Testing recap
- [ ] Creating a framework from scratch

Our next step is to pick the topic from this short list and we're done with this issue.

**Comment by priestine** [comment]
After an internal poll, Accessibility is the topic chosen based on the highest amount of participation.
